/**
* Generated by go-doudou v2.1.6.
* You can edit it as your need.
 */
package config

import (
	"github.com/kelseyhightower/envconfig"
	"github.com/unionj-cloud/go-doudou/v2/framework/config"
	"github.com/unionj-cloud/go-doudou/v2/toolkit/errorx"
)

var G_Config *Config

func init() {
	G_Config = LoadFromEnv()
}

type Config struct {
	Source struct {
		Addr              string
		User              string
		Pass              string
		IncludeTableRegex []string
		ExcludeTableRegex []string
		Migrate           bool
		Databases         []string
		Dump              bool
		Sync              bool
		Handler           string
		DumpBatchSize     int
		TargetDbSuffix    string
	}
	config.Config
}

func LoadFromEnv() *Config {
	var conf Config
	err := envconfig.Process("canal", &conf)
	if err != nil {
		errorx.Panic("Error processing environment variables")
	}
	return &conf
}
