/**
* Generated by go-doudou v2.1.6.
* You can edit it as your need.
 */
package config

import (
	"github.com/kelseyhightower/envconfig"
	"github.com/unionj-cloud/go-doudou/v2/framework/config"
	"github.com/unionj-cloud/go-doudou/v2/toolkit/errorx"
)

type Config struct {
	Source struct {
		Addr              string
		User              string
		Pass              string
		IncludeTableRegex []string
	}
	config.Config
}

func LoadFromEnv() *Config {
	var conf Config
	err := envconfig.Process("canal", &conf)
	if err != nil {
		errorx.Panic("Error processing environment variables")
	}
	return &conf
}
